import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Root } from "@/layout/root/Root";
import { Header } from "@/layout/header/Header";
import { Drawer } from "@/layout/drawer/Drawer";
import { Sidebar } from "@/layout/sidebar/Sidebar";
import { Container } from "@/layout/container/Container";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth text-base">
      <body className={inter.className}>
        <Root>
          <Header />
          <Sidebar />
          <Container>{children}</Container>
          <Drawer />
        </Root>
      </body>
    </html>
  );
}
